#!/bin/bash
# Fix all UI issues in one go

# 1. Update index.html - remove dumb text, add filter container
cat > index.html << 'HTML_EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Release Wall</title>
    <link rel="stylesheet" href="assets/styles.css">
</head>
<body>
    <header>
        <h1>NEW RELEASE WALL</h1>
        <div id="genre-filters" class="filters">
            <!-- Generated by JS -->
        </div>
    </header>
    <main id="wall"></main>
    <script src="assets/app.js"></script>
</body>
</html>
HTML_EOF

echo "✓ Fixed index.html"
