min_rotten_tomatoes: 0
omdb:
  api_key: YOUR_REAL_KEY_HERE
omdb_api_key: 539723d9
site_title: The New Release Wall
tmdb:
  bearer: YOUR_LONG_BEARER
tmdb_api_key: 99b122ce7fa3e9065d7b7dc6e660772d
release_mode: provider
server_port: 3001
offline: true
fetch_tmdb: false
fetch_rt: false
fetch_trailers: false
