name: Daily Provider Check
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python movie_tracker.py check
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add movie_tracking.json
          git diff --staged --quiet || git commit -m "Daily check - $(date -u +%Y-%m-%d)"
          git push
