name: Daily Update (Automated)
on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC = 1 AM PST / 2 AM PDT
  workflow_dispatch:  # Allow manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Python dependencies
        run: |
          pip install requests pyyaml beautifulsoup4 lxml selenium webdriver-manager playwright

      - name: Install Playwright browsers
        run: |
          playwright install chromium --with-deps

      - name: Run daily orchestrator
        env:
          AGENT_SCRAPER_ENABLED: true  # Set to false to disable agent scraping
        run: python3 daily_orchestrator.py

      - name: Commit and push changes
        run: |
          git config user.email "action@github.com"
          git config user.name "NRW Daily Bot"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily update - $(date -u +%Y-%m-%d) [automated]"
            git push
          fi
